title: Baylee Christensen
description: Graduate Research Assistant | Ph. D. Student in Ecology and Evolution | University of Wyoming
show_downloads: False
google_analytics: G-BRGD28TNRY
logo: docs/assets/dfasdf.png
remote_theme: pages-themes/cayman@v0.2.0
