title: Baylee Christensen
description: Graduate Research Assistant | Ph. D. Student in Ecology and Evolution | University of Wyoming
show_downloads: False
google_analytics: G-BRGD28TNRY
logo: docs/assets/dfasdf.png
theme: jekyll-theme-cayman
